{% set version = "1.0.0" %}

package:
  name: spectralib
  version: {{ version }}

source:
  fn: spectralib-{{ version }}.tar.gz
  url: https://github.com/yixuan/spectra/archive/v{{ version }}.tar.gz
  sha256: 45228b7d77b916b5384245eb13aa24bc994f3b0375013a8ba6b85adfd2dafd67

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - eigen
  run:
    - eigen

test:
  commands:
    - test -f ${PREFIX}/include/Spectra/GenEigsSolver.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\\include\\Spectra\\GenEigsSolver.h exit 1  # [win]

about:
  home: https://spectralib.org/
  license: MPL-2.0
  license_file: LICENSE
  summary: A header-only C++ library for large scale eigenvalue problems

extra:
  recipe-maintainers:
    - jschueller
